version: "3.9"

services:
  db:
    image: postgres:15
    container_name: contacts-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: contacts-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

